#!/bin/sh


APP_DIR="$(dirname "$0")/../.."
WORKSPACE_DIR="$APP_DIR/.."

if test "$1" != "--update-app-name-only"; then
  open -b com.microsoft.VSCode "$WORKSPACE_DIR"
fi

ABS_WORKSPACE_DIR="$(cd "$WORKSPACE_DIR" && pwd)"
WORKSPACE_NAME="$(basename "$ABS_WORKSPACE_DIR")"

echo "CFBundleDisplayName = \"$WORKSPACE_NAME\";" > "$APP_DIR/Contents/Resources/English.lproj/InfoPlist.strings"
# ABS_SRC_APP_DIR="$(cd "$APP_DIR" && pwd)"
# ABS_DST_APP_DIR="$ABS_WORKSPACE_DIR/$WORKSPACE_NAME.app"
# mv -- "$ABS_SRC_APP_DIR" "$ABS_DST_APP_DIR"
